version: '2'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'

  web:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - './:/app'
    working_dir: /app
    command: ./start.sh
    environment:
      - MIX_ENV=dev
      - PORT=4000
    links:
      - db:db