version: '2'

services:
  db:
    image: postgres
    networks:
      - default
      - outside
    ports:
      - '5432:5432'

  web:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - './:/app'
    working_dir: /app
    command: mix phoenix.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    links:
      - db:db
    networks:
      - default
      - outside

networks:
  outside:
    external: true
